/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mandelbrots;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.MemoryImageSource;
import java.util.Stack;

/**
 *
 * @author istolcers
 */
public class Sets extends javax.swing.JFrame {

    /**
     * Creates new form Sets
     */
    public Sets() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        zoomOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Zīmēt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jTextField1.setText("-1");

        jTextField2.setText("-1");

        jTextField3.setText("1");

        jTextField4.setText("1");

        jLabel1.setText("x sākums");

        jLabel2.setText("x beigas");

        jLabel3.setText("y sākums");

        jLabel4.setText("y beigas");

        zoomOut.setText("ZoomOut");
        zoomOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                .addComponent(jTextField2))
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField4)
                                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(zoomOut)
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(zoomOut)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        x1=Double.parseDouble(jTextField1.getText());
        x2=Double.parseDouble(jTextField3.getText());
        y1=Double.parseDouble(jTextField2.getText());
        y2=Double.parseDouble(jTextField4.getText());
        izsaukt(x1, x2, y1, y2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        int x=evt.getX();
        int y=evt.getY();
        zx1=x1+x*(x2-x1)/400;
        zy2=y2-y*(y2-y1)/400;
        iks=x;
        igr=y;
    }//GEN-LAST:event_jPanel1MousePressed
int iks=0;
int igr=0;
    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        steks.push(x1);
        steks.push(x2);
        steks.push(y1);
        steks.push(y2);
        int x=evt.getX();
        int y=evt.getY();
        if(x-iks>y-igr){
            x=iks+y-igr;
        }
        else{
            y=igr+x-iks;
        }
        zx2=x1+x*(x2-x1)/400;
        zy1=y2-y*(y2-y1)/400;
        jTextField1.setText(String.valueOf(zx1));
        jTextField2.setText(String.valueOf(zy1));
        jTextField3.setText(String.valueOf(zx2));
        jTextField4.setText(String.valueOf(zy2));
        izsaukt(zx1, zx2, zy1, zy2);
        x1=zx1;
        x2=zx2;
        y1=zy1;
        y2=zy2;
    }//GEN-LAST:event_jPanel1MouseReleased

    private void zoomOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomOutActionPerformed
        if(!steks.isEmpty()){
            double a4=steks.pop();
            double a3=steks.pop();
            double a2=steks.pop();
            double a1=steks.pop();
            jTextField1.setText(String.valueOf(a1));
            jTextField2.setText(String.valueOf(a3));
            jTextField3.setText(String.valueOf(a2));
            jTextField4.setText(String.valueOf(a4));
            izsaukt(a1, a2, a3, a4);
            x1=a1;
            x2=a2;
            y1=a3;
            y2=a4;
        }
    }//GEN-LAST:event_zoomOutActionPerformed

    /**
     * @param args the command line arguments
     */
    Stack<Double> steks=new Stack();
    
    //mainīgie zoom funkcijai
    double zx1=0;
    double zx2=0;
    double zy1=0;
    double zy2=0;
    public void izsaukt(double x1, double x2, double y1, double y2){
        Graphics g=jPanel1.getGraphics();
        zimet(x1, x2, y1, y2);
        img=createImage(new MemoryImageSource(jPanel1.getWidth(), jPanel1.getHeight(), pixels, 0, jPanel1.getWidth()));
        g.drawImage(img, 0, 0, null);
    }
    //globālie mainīgie intervālam
    double x1=-1;
    double x2=1;
    double y1=-1;
    double y2=1;
    int[] pixels=new int[400*400];
    int[] krasa=new int[400*400];
    Image img;
    public void zimet(double x1, double x2, double y1, double y2){
        aprekins(x1, x2, y1, y2);
        for (int i=0; i<pixels.length; i++){
            int y=krasa[i];
            if(y>=100){
                pixels[i]=(255<<24)|(0<<16)|(0<<8)|0;
            }
            else{
                pixels[i]=(255<<24)|((10*y)%256<<16)|((10*y)%256<<8)|255;
                /*if(krasa[i]>=50&&krasa[i]<100){
                    pixels[i]=(255<<24)|(0<<16)|(0<<8)|153;
                }
                else{
                    if(krasa[i]>=20&&krasa[i]<50){
                        pixels[i]=(255<<24)|(0<<16)|(128<<8)|255;
                    }
                    else{
                        pixels[i]=(255<<24)|(153<<16)|(204<<8)|255;
                    }
                }*/
            }
        }
    }
    public void aprekins(double x1, double x2, double y1, double y2){
        double m=10;
        double wid=x2-x1;
        double he=y2-y1;
        for(int i=0; i<400; i++){
            for(int j=0; j<400; j++){
                double im=y2-i*he/400;
                double re=x1+j*wid/400;
                double cre=re;
                double cim=im;
                int k=0;
                double zmod=0;
                do{
                    double rej=Math.pow(re, 2)-Math.pow(im, 2)+cre;
                    double imj=2*re*im+cim;
                    zmod=Math.pow(rej, 2)-Math.pow(imj, 2);
                    re=rej;
                    im=imj;
                    k++;
                }while(k<100&&zmod<=m);
                krasa[i*400+j]=k;
            }
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton zoomOut;
    // End of variables declaration//GEN-END:variables
}
